//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEnrollCourse
    {
        public int Id { get; set; }
        public string StudentRegNo { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
